name: ML Pipeline CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas numpy pyarrow
          CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-2.7.1/constraints-${PYTHON_VERSION}.txt"
          pip install "apache-airflow==2.7.1" --constraint "${CONSTRAINT_URL}"
      - name: Run Unit Tests
        run: |
          pytest tests/